global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: json_exporter
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets:
          - http://127.0.0.1:10102/json_rpc
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:7979
